# Default values for gorest-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/datasine-158109/gorest 
  tag: 0.1
  pullPolicy: Always
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - chart-example.local
postgresql:
  user: test
  password: password
  db: test
  host: "127.0.0.1"
